version: '3.5'

services:
  api:
    build:
      args:
        user: gdeleon
        uid: 1000
      context: ./api
      dockerfile: Dockerfile
    container_name: 'gpo_axo-api'
    restart: 'always'
    image: gpo_axo-api
    container_name: gpo_axo-api
    volumes:
      - './api:/var/www'
    networks:
      - gpo_axo
  db:
    image: mysql:8.0
    container_name: gpo_axo-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: gpo_axo
      MYSQL_ROOT_PASSWORD: $gpo_axo.123
      MYSQL_PASSWORD: $gpo_axo.123
      MYSQL_USER: gpo_axo
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - gpo_axo
  nginx:
    image: nginx:1.17-alpine
    container_name: gpo_axo-nginx
    restart: unless-stopped
    ports:
      - 9001:80
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - gpo_axo
networks:
  gpo_axo:
    driver: bridge
